name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_TAG: ${{ env.TAG_NAME }}

jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.IMAGE_TAG }}
      
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag image:${{ env.IMAGE_TAG }}
      - name: Push the tagged Docker image
        run: docker push image:${{ env.IMAGE_TAG }}
