name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_TAG: ${{ env.TAG_NAME }}

jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.IMAGE_TAG }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: monImage:${{ env.IMAGE_TAG }}
          push: true
