name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - name: Log into the Container registry
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      - name: Push the tagged Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
