name: Build and push Docker image

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log into the Container registry
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: get TAG_NAME
        id: set-env
        run: echo "::set-env name=TAG_NAME::$(echo $GITHUB_REF | awk -F '/' '{print $3}')"
      
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ steps.set-env.outputs.TAG_NAME }}
      - name: Push the tagged Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.set-env.outputs.TAG_NAME }}
