name: triggered_manually

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Docker_login
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Docker_setup
                uses: docker/setup-buildx-action@v2
            -
                name: Build&Push
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox: latest
